version: 2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.4-jessie-node-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Reset shallow clone
          command: |
            [[ ! -s \"$(git rev-parse --git-dir)/shallow\" ]] || git fetch --unshallow
            git fetch origin $CIRCLE_BRANCH
      - run:
          name: Install
          command: |
            gem install bundler
            gem install rspec
            npm i
      - run:
          name: Compile
          command: |
            npm run compile
            npm run compile-dev
      - run:
          name: Test
          command: npm run -s test-cov
      - run:
          name: Analyze
          command: npm run -s vile
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
